# -*- coding: utf-8 -*-
"""2_Candidate_Elimination_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwK-z3qBOqGjg6tC306O5xEj-NNrd0FP
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

def find_s_algorithm(csv_path):
    data = pd.read_csv(csv_path)
    print("Training data:")
    print(data)

    attributes = data.iloc[:, :-1].values
    target = data.iloc[:, -1].values

    hypothesis = ['0'] * len(attributes[0])

    for i, row in enumerate(attributes):
        if target[i].strip().lower() == 'yes':
            if hypothesis == ['0'] * len(row):
                hypothesis = list(row)
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != row[j]:
                        hypothesis[j] = '?'
    return hypothesis

final_hypothesis = find_s_algorithm('finds_data.csv')
print("\nMost specific hypothesis found by FIND-S:")
print(final_hypothesis)

from google.colab import files
uploaded = files.upload()  # select candidate_elimination_data.csv

import pandas as pd
import numpy as np

def candidate_elimination(csv_path):
    data = pd.read_csv(csv_path)
    print("Training data:")
    print(data)

    concepts = data.iloc[:, :-1].values
    target = data.iloc[:, -1].values

    n_attributes = concepts.shape[1]

    specific_h = list(concepts[0])
    general_h = [['?' for _ in range(n_attributes)] for _ in range(n_attributes)]

    for i, instance in enumerate(concepts):
        if target[i].strip().lower() == 'yes':
            for x in range(n_attributes):
                if instance[x] != specific_h[x]:
                    specific_h[x] = '?'
                    general_h[x][x] = '?'
        else:
            for x in range(n_attributes):
                if instance[x] != specific_h[x]:
                    general_h[x][x] = specific_h[x]
                else:
                    general_h[x][x] = '?'

    general_h = [h for h in general_h if h != ['?'] * n_attributes]

    return specific_h, general_h

S_final, G_final = candidate_elimination('candidate_elimination_data.csv')

print("\nFinal Specific Hypothesis (S):")
print(S_final)
print("\nFinal General Hypotheses (G):")
for h in G_final:
    print(h)

from google.colab import files
uploaded = files.upload()  # select id3_playtennis.csv

import pandas as pd
import numpy as np
import math

def entropy(target_col):
    values, counts = np.unique(target_col, return_counts=True)
    probs = counts / counts.sum()
    return -sum(p * math.log2(p) for p in probs if p > 0)

def info_gain(data, split_attr, target_name):
    total_entropy = entropy(data[target_name])
    values, counts = np.unique(data[split_attr], return_counts=True)
    weighted_entropy = sum(
        (counts[i] / counts.sum()) * entropy(data[data[split_attr] == values[i]][target_name])
        for i in range(len(values))
    )
    return total_entropy - weighted_entropy

def id3(data, original_data, features, target_name, parent_class=None):
    if len(np.unique(data[target_name])) <= 1:
        return np.unique(data[target_name])[0]
    if len(data) == 0:
        return np.unique(original_data[target_name])[
            np.argmax(np.unique(original_data[target_name], return_counts=True)[1])
        ]
    if len(features) == 0:
        return parent_class

    parent_class = np.unique(data[target_name])[
        np.argmax(np.unique(data[target_name], return_counts=True)[1])
    ]

    gains = [info_gain(data, feature, target_name) for feature in features]
    best_feature = features[np.argmax(gains)]

    tree = {best_feature: {}}
    remaining_features = [f for f in features if f != best_feature]

    for value in np.unique(data[best_feature]):
        sub_data = data[data[best_feature] == value]
        subtree = id3(sub_data, data, remaining_features, target_name, parent_class)
        tree[best_feature][value] = subtree

    return tree

def predict(query, tree, default='Yes'):
    for attribute in query:
        if attribute in tree:
            try:
                result = tree[attribute][query[attribute]]
            except KeyError:
                return default
            if isinstance(result, dict):
                return predict(query, result, default)
            else:
                return result
    return default

data = pd.read_csv('id3_playtennis.csv')
print("Training data:")
print(data)

target_name = 'PlayTennis'
features = [c for c in data.columns if c != target_name]

tree = id3(data, data, features, target_name)

print("\nLearned Decision Tree:")
import pprint
pprint.pprint(tree)

new_sample = {
    'Outlook': 'Sunny',
    'Temperature': 'Cool',
    'Humidity': 'High',
    'Wind': 'Strong'
}

prediction = predict(new_sample, tree)
print("\nNew sample:", new_sample)
print("Predicted PlayTennis:", prediction)