# -*- coding: utf-8 -*-
"""1_FIND_S_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXSFkCfQ5gIwowPbMqLuq5FUdm1Oa3rV
"""

from google.colab import files
uploaded = files.upload()  # select finds_data.csv

import pandas as pd

def find_s_algorithm(csv_path):
    data = pd.read_csv(csv_path)
    print("Training data:")
    print(data)

    attributes = data.iloc[:, :-1].values
    target = data.iloc[:, -1].values

    hypothesis = ['0'] * len(attributes[0])

    for i, row in enumerate(attributes):
        if target[i].strip().lower() == 'yes':
            if hypothesis == ['0'] * len(row):
                hypothesis = list(row)
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != row[j]:
                        hypothesis[j] = '?'
    return hypothesis

final_hypothesis = find_s_algorithm('finds_data.csv')
print("\nMost specific hypothesis found by FIND-S:")
print(final_hypothesis)
