# -*- coding: utf-8 -*-
"""exp 9-15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0zyAQdzNuHLusG5q0lsWn3ASDLIB7D3
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

x=np.array([1,2,3,4,5]).reshape(-1,1)
y=np.array([2,4,5,4,5])

l=LinearRegression().fit(x,y)
p=PolynomialFeatures(2)
xp=p.fit_transform(x)
pr=LinearRegression().fit(xp,y)

plt.scatter(x,y)
plt.plot(x,l.predict(x),label="Linear")
plt.plot(x,pr.predict(xp),label="Polynomial")
plt.legend()
plt.show()

import numpy as np
from sklearn.mixture import GaussianMixture

x=np.array([[1],[2],[3],[10],[11],[12]])
model=GaussianMixture(n_components=2,random_state=0)
model.fit(x)

print("Means:",model.means_.ravel())
print("Labels:",model.predict(x))

from sklearn.tree import DecisionTreeClassifier

x=[[20,50000],[30,70000],[40,90000],[22,30000],[35,80000]]
y=["Poor","Good","Good","Poor","Good"]

model=DecisionTreeClassifier()
model.fit(x,y)

print(model.predict([[28,60000]]))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

x,y=load_iris(return_X_y=True)
a,b,c,d=train_test_split(x,y,test_size=.2,random_state=1)

model=KNeighborsClassifier(3)
model.fit(a,c)

print("Accuracy:",model.score(a,c))
print("Prediction:",model.predict([x[0]]))

from sklearn.linear_model import LinearRegression

x=[[5,50000],[4,40000],[3,30000],[2,20000],[6,60000]]
y=[500000,400000,300000,200000,600000]

model=LinearRegression()
model.fit(x,y)

print("Predicted price:",model.predict([[4,45000]]))

from sklearn.linear_model import LinearRegression

x=[[1,1000],[2,1500],[3,2000],[4,2500],[5,3000]]
y=[20,30,40,50,60]

model=LinearRegression()
model.fit(x,y)

print("Predicted price:",model.predict([[3,2200]]))

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

x,y=load_iris(return_X_y=True)
a,b,c,d=train_test_split(x,y,test_size=.2,random_state=1)

model=GaussianNB()
model.fit(a,c)

print("Accuracy:",model.score(b,d))
print("Prediction:",model.predict([x[0]]))
